#!/bin/bash

# we break the legitimate traffic pcap file(newcapture.pcap) into smaller ones which correspond to captures lasting 300 seconds
rm -rf ./legit_traffic
mkdir ./legit_traffic
editcap -i 300 newcapture.pcap ./legit_traffic/legit_traffic.pcap

rm -rf ./legit_traffic_flows
mkdir ./legit_traffic_flows

output_path="./legit_traffic_flows/"
format="%IPV4_SRC_ADDR %IPV4_DST_ADDR %IN_PKTS %OUT_PKTS %IN_BYTES %OUT_BYTES %PROTOCOL %ICMP_TYPE %TCP_FLAGS %L4_SRC_PORT %L4_DST_PORT %SRC_AS %DST_AS %FLOW_START_MILLISECONDS %FLOW_END_MILLISECONDS"

# we keep the default values of nProbe
lifetime_timeout=120 # default 120 seconds
idle_timeout=30 # default 30 seconds

pcaps=./legit_traffic/*
for p in $pcaps
do
    nprobe -V 9 -i $p --dont-nest-dump-dirs -P ${output_path} -T "${format}" -t ${lifetime_timeout} -d ${idle_timeout} -W
done
 
