#!/bin/bash

rm -rf ./port_scan_flows
mkdir ./port_scan_flows

#--dont-drop-privileges
output_path="./port_scan_flows/"
format="%IPV4_SRC_ADDR %IPV4_DST_ADDR %IN_PKTS %OUT_PKTS %IN_BYTES %OUT_BYTES %PROTOCOL %ICMP_TYPE %TCP_FLAGS %L4_SRC_PORT %L4_DST_PORT %SRC_AS %DST_AS %FLOW_START_MILLISECONDS %FLOW_END_MILLISECONDS"

# we keep the default values of nProbe
lifetime_timeout=120 # default 120 seconds
idle_timeout=30 # default 30 seconds

pcaps=./port_scan/*
for p in $pcaps
do
    nprobe -V 9 -i $p --dont-nest-dump-dirs -P ${output_path} -T "${format}" -f "ip proto 6" -t ${lifetime_timeout} -d ${idle_timeout} -W
done

